package com.frynetworks.fryapp.network.dashboard

import com.google.gson.JsonArray
import com.google.gson.JsonElement
import com.google.gson.JsonObject
import com.google.gson.JsonParser
import org.junit.Assert.assertEquals
import org.junit.Assert.assertThrows
import org.junit.Test

/**
 * The dashboard signs `${METHOD}|${path}|${JSON.stringify(body)}|${ts}` and re-stringifies the
 * PARSED body on the server, so the app has to emit byte-identical `JSON.stringify` output:
 * insertion-ordered keys, no whitespace, JS number formatting, JS string escaping.
 * Vectors in fixtures/canonical/vectors.json are generated by Node (tools/bridge/vectors/gen.mjs).
 */
class CanonicalJsonTest {

    private fun vectors(): JsonArray {
        val text = javaClass.classLoader!!.getResource("fixtures/canonical/vectors.json")!!.readText()
        return JsonParser.parseString(text).asJsonArray
    }

    /** Gson's JsonObject keeps insertion order, so this mirrors what a Kotlin caller would build. */
    private fun toKotlin(e: JsonElement): Any? = when {
        e.isJsonNull -> null
        e.isJsonArray -> e.asJsonArray.map { toKotlin(it) }
        e.isJsonObject -> LinkedHashMap<String, Any?>().apply { e.asJsonObject.entrySet().forEach { (k, v) -> put(k, toKotlin(v)) } }
        e.asJsonPrimitive.isBoolean -> e.asBoolean
        e.asJsonPrimitive.isString -> e.asString
        else -> e.asJsonPrimitive.asBigDecimal.let { if (it.scale() <= 0) it.toLong() else it.toDouble() }
    }

    @Test
    fun `every Node vector stringifies byte-identically`() {
        for (v in vectors()) {
            val o = v.asJsonObject
            assertEquals(o["canonical"].asString, JsJson.stringify(toKotlin(o["body"])))
        }
    }

    @Test
    fun `jsonBody builder keeps insertion order and omits nothing`() {
        val body = jsonBody {
            "miner_key" to "FEM-ABC"
            "no" to 3
            "preview" to true
        }
        assertEquals("""{"miner_key":"FEM-ABC","no":3,"preview":true}""", JsJson.stringify(body))
    }

    @Test
    fun `strings escape quotes, backslashes and control characters the way JS does`() {
        assertEquals("\"a\\\"b\\\\c\\n\\t\\u0001\"", JsJson.stringify("a\"b\\c\n\t"))
    }

    @Test
    fun `non-ASCII characters are emitted raw like JSON stringify`() {
        assertEquals("\"café — 中\"", JsJson.stringify("café — 中"))
    }

    @Test
    fun `doubles are rejected because JS and Gson format them differently`() {
        assertThrows(IllegalArgumentException::class.java) { JsJson.stringify(mapOf("amount" to 12.5)) }
    }

    @Test
    fun `integer-like object keys are rejected because V8 reorders them`() {
        assertThrows(IllegalArgumentException::class.java) { JsJson.stringify(mapOf("10" to 1, "a" to 2)) }
    }

    @Test
    fun `nulls, booleans, longs, nested lists and objects`() {
        val body: Map<String, Any?> = linkedMapOf(
            "a" to linkedMapOf("b" to listOf(1L, 2, linkedMapOf("c" to null))),
            "d" to false,
            "e" to 9007199254740991L,
        )
        assertEquals("""{"a":{"b":[1,2,{"c":null}]},"d":false,"e":9007199254740991}""", JsJson.stringify(body))
    }
}
